import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Container } from "@/components/Container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div>
          <Header/>
          <main className="pt-[var(--navigation-height)]">{children}</main>
          <footer>
            <Container>footer</Container>
          </footer>
        </div>
      </body>
    </html>
  );
}
